### ISSUE TITLE
To remove the sound pitch limit completely

### ISSUE THREAD

**Issue by Kouzeru** [LLK/scratch-audioengine#174]
It's my second suggestion about the pitch limit, I hope you understand this @ericrosenbaum
 
Many _**advanced**_ Scratchers had complaint this limitations, mainly implementing audio pause function, and (specific) audio stop function, and I don't really think there's projects rely on this current behavior. It's discovered on Turbowarp that, removing these limitation would achieve these both features without a need of new blocks:

![image](https://user-images.githubusercontent.com/46141631/131269416-ee395287-7f16-4bff-80ec-19cf93c845fd.png)
![image](https://user-images.githubusercontent.com/46141631/131269420-52aa32d3-6e2b-452e-a113-6616486350af.png)

One can pause audio by simply setting the **pitch effect to very-low-value**, and resuming it by resetting it back to 0.
One can also stop the specific audio that currently playing by setting the **pitch effect to very-high-value**

This has a significant impact upon how Scratchers "see" the current vanilla.

**Comment by ericrosenbaum** [comment]
Thanks for this suggestion @Kouzeru. I will try to explain here why we will probably keep the current behavior, and how we might consider a corresponding feature request.

The current behavior of limiting the pitch effect to three octaves up and down (-360 to 360) is intended to prevent confusion for beginners. 

You can think of it as analogous to the "fencing" behavior for the positions of sprites: when a sprite's x or y position is set to an extreme value like -99999, the sprite only goes partway off the edge, instead of disappearing completely. This helps beginners understand what happened when they try something very typical for beginners, such as "forever change x by 1000" or "set x to -999999". They can see what happened ("oh, it went off to the left!"), and recover from it (you can still drag the sprite back to where you wanted it). Without fencing, your sprite would disappear, and you may not know why, or how to get it back.

The pitch effect is much more abstract, because it is hidden state (you cannot see the value, and it only takes effect while a sound is playing). Beginners will typically do something like "forever change pitch effect by 10" or "set pitch effect to -99999". They may have no idea what to expect when they run these blocks, e.g. if they do not know what "pitch" means. Without the limits, the sound would become inaudible, and all sound from that sprite will seem completely broken. They may not know what has occurred or why, or how to recover ("is my volume off? are all sounds broken?").

With the current limits in place, the sound will still play, and be audible. The idea is that the person can at least hear that a sound has played. They may be able to recover using the pitch blocks (e.g. if you do "set pitch effect to -99999" and then "change pitch by 10", you may be able to hear the change from -360 to -350). This is not perfect, but seems to me to be better for beginners than the behavior without the limits.

The other thing for us to consider is how we might separate the feature request from the proposed solution. Sounds like turbowarp now has the ability to pause and unpause sounds, which is super cool! My question is: if we want to add that feature, how could we make it friendly and accessible, instead of a hidden feature? One way would be to add one or more blocks for controlling the sound in new ways (e.g. pause/unpause, jump to a certain time, a hat block to trigger when the sound reaches a certain time, etc.). We haven't really considered this space of possibilities in detail. It might make an interesting exploration to prototype these new blocks. It's not clear to me if they should be added to the "sounds" category or become a separate extension for advanced sound things.
